// Auto-generated by generate-pages-meta.cjs
export default {
  "250603-home-remodeling": "2025-06-10T05:34:22.000Z",
  "250605-classinequity2": "2025-06-10T05:34:22.000Z",
  "250605-home-efficiency": "2025-06-10T05:34:22.000Z",
  "250605-home_basics_quiz": "2025-06-10T05:34:22.000Z",
  "250605-plants-quiz": "2025-06-10T05:34:22.000Z",
  "250606-mcp_quiz-2": "2025-06-10T05:34:22.000Z",
  "250606-mcp_quiz-v3": "2025-06-10T05:34:22.000Z",
  "250606-remodel_rim_joist_related_quiz": "2025-06-10T05:34:22.000Z",
  "250609-intermittentfastingquiz": "2025-06-10T05:34:22.000Z",
  "TestPage": "2025-06-10T05:34:22.000Z",
  "bond-yield-quiz2": "2025-06-10T05:34:22.000Z",
  "daliochatgptquiz": "2025-06-10T05:34:22.000Z",
  "economic-indicators-dashboard": "2025-06-10T05:34:22.000Z",
  "market-relationships-charts": "2025-06-10T05:34:22.000Z",
  "wine-quiz": "2025-06-10T05:34:22.000Z"
} as Record<string, string>;
